### ISSUE TITLE
KPN addon not working anymore due to url change

### ISSUE THREAD

**Issue by 3dw1n** [3DSBricker/dut-iptv#6]
The url has changed from api.tv.kpn.com to api.tv.prod.itvavs.prod.aws.kpn.com.

I got it working again by modifying the 8th line in /storage/.kodi/addons/plugin.video.kpn/resources/lib/constants.py to:
'api': 'https://api.tv.prod.itvavs.prod.aws.kpn.com/101/1.2.0/A/nld/pctv/kpn',

Maybe you can include this so other ppl can use their KPN Addon again also, thx!

UPDATE: looks like api.prd.tv.kpn.com is the main url
```
host api.prd.tv.kpn.com
api.prd.tv.kpn.com is an alias for api.tv.prod.itvavs.prod.aws.kpn.com
```

**Comment by Nigel1992** [comment]
Merge commit added at https://github.com/3DSBricker/dut-iptv/pull/7
Thanks for the info @3dw1n

**Comment by 3DSBricker** [comment]
Thanks! It's merged!
